spring:
  config:
    import: classpath:credentials-config.yaml
  cassandra:
    contact-points:
      - 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: market_data
    schema-action: none
server:
  port: 8081
